spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/library_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:altyn297009}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

spring.flyway.enabled=true
spring.flyway.repair-on-migrate=false
spring.flyway.locations=classpath:db/migration
spring.jpa.hibernate.ddl-auto=none

logging.level.com.example.library=INFO
logging.level.org.springframework.jdbc.core=DEBUG